server:
  port: 9527

spring:
  application:
    name: springcloud-zuul #微服务名称

#Eureka的配置 服务注册到哪里去
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: zuul-9527 #修改Eureka上的默认描述信息
    prefer-ip-address: true #隐藏ip
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept #微服务名称
    mydept.path: /mydept/** #路由后指定路径
  #ignored-services: springcloud-provider-dept #不能再使用这个路径访问  * 隐藏全部的微服务
  ignored-services: "*"
  prefix: /study #统一的访问公共前缀